=== apoomjoshi/Hands-on-code/git_repo/Web_Services_workspace/PatientXML/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.UdemyCourse.com/Patient"
	xmlns:tns="http://www.UdemyCourse.com/Patient" elementFormDefault="qualified">
	
	<element name="patient" type="tns:Patient"/>
	
	<complexType name="Patient">
	<sequence>
		<element name="id" type="tns:ID" maxOccurs="2"/>
		<element name="name" type="tns:Sting15chars"/>
		<element name="age" type="int"/>
		<element name="dob	" type="date"/>
		<element name="email" type="string" maxOccurs="unbounded"/>
		<element name="gender" type="tns:Gender"/>
		<element name="phone" type="string"/>
		<element name="payment" type="tns:PaymentType"/>
	</sequence>
	</complexType>
	
	<complexType name="PaymentType">
	<choice>
		<element name="cash" type="int"></element>
		<element name="insurance" type="tns:insurance"></element>
	</choice>
	</complexType>
	
	<complexType name="insurance">
	<all>
	<element name="provider" type="string"></element>
	<element name="limit" type="int"></element>
	</all>
	
	</complexType>
	
	<simpleType name="ID">
	<restriction base="string">
	<pattern value="[0-9]*"></pattern>
	</restriction>
	</simpleType>
	
	
	<simpleType name="Sting15chars">
	<restriction base="string">
	<maxLength value="15"></maxLength>
	<minLength value="5"></minLength>
	</restriction>
	</simpleType>
	
	<simpleType name="Gender">
	<restriction base="string">
	<enumeration value="M"/>
	<enumeration value="F"/>
	</restriction>
	</simpleType>
</schema>

=== apoomjoshi/Hands-on-code/git_repo/Web_Services_workspace/PatientXML/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.UdemyCourse.com/Patient" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.UdemyCourse.com/Patient Patient.xsd ">
  <tns:id>1</tns:id>
   <tns:id>1</tns:id>
  <tns:name>apoorva</tns:name>
  <tns:age>27</tns:age>
  <tns:dob>2001-01-01</tns:dob>
  <tns:email>tns:email</tns:email>
  <tns:gender>F</tns:gender>
  <tns:phone>tns:phone</tns:phone>
  <tns:payment>
    <tns:insurance>
    	<tns:limit>1000</tns:limit>
    	<tns:provider>Cigna</tns:provider>
    </tns:insurance>
  </tns:payment>
</tns:patient>
